version: '3.7'
services:

  db:
    image: postgres:15
    env_file:
      - docker.env
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    depends_on:
      - db
    env_file:
      - docker.env
    ports:
      - '8000:8000'
