version: "3.7"
services:

  db:
    image: postgres:15
#    restart: always
    environment:
      POSTGRES_DB: vanessa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5832:5432"

  app:
    container_name: app
    build:
      context: .
    depends_on:
      - db
    env_file:
      - docker.env
    ports:
      - "8000:8000"
