version: '3.7'
services:

  db:
    image: postgres:15
    env_file:
      - docker.env
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '5370:5370'

  app:
    build:
      context: .
    depends_on:
      - db
      - redis
    env_file:
      - docker.env
    ports:
      - '8000:8000'
